# Generated by Django 5.0.2 on 2024-03-25 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_otpcode_otp'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient'),
        ),
    ]
