# Generated by Django 5.0.2 on 2024-04-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_session_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
