# Generated by Django 5.0.2 on 2024-04-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_alter_otpcode_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('state', models.CharField(choices=[('free', 'Free'), ('booked', 'Booked')], default='free', max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='accounts.doctor')),
                

            ],
        ),
    ]
