# Generated by Django 5.0.2 on 2024-04-12 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_otpcode_otp'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointement',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient'),
        ),
        migrations.AddField(
            model_name='appointement',
            name='session_length',
            field=models.DurationField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointement',
            unique_together={('day', 'date', 'start_at', 'end_at', 'doctor')},
        ),
        migrations.RemoveField(
            model_name='appointement',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointement',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
    ]
