# Generated by Django 5.0.2 on 2024-04-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_appointement_patient_alter_appointement_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointement',
            old_name='patient',
            new_name='user',
        ),
    ]
