# Generated by Django 5.0.2 on 2024-05-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_otpcode_otp'),
        ('reservations', '0005_rename_patient_appointement_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointement',
            unique_together={('day', 'date', 'start_at', 'doctor')},
        ),
        migrations.RemoveField(
            model_name='appointement',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='appointement',
            name='session_length',
        ),
    ]
