# Generated by Django 5.0.2 on 2024-03-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_image_alter_doctor_gender_alter_doctor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(upload_to='accounts/images/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='otp',
            field=models.CharField(default='6c21c', max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(upload_to='accounts/images/%Y/%m/%d/%H/%M/%S/'),
        ),
    ]
