# Generated by Django 5.0.2 on 2024-03-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctor_image_alter_otpcode_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='otp',
            field=models.CharField(default='a2068', max_length=6),
        ),
    ]
