# Generated by Django 5.0.2 on 2024-03-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_otpcode_otp_alter_otpcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='accounts/images/carton.png', null=True, upload_to='accounts/images/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='otp',
            field=models.CharField(default='3841c', max_length=6),
        ),
    ]
