# Generated by Django 5.0.2 on 2024-04-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profileimage_delete_photo_remove_doctor_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='user',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='doctor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='otp',
            field=models.CharField(default='396cf', max_length=6),
        ),
    ]
