# Generated by Django 5.0.2 on 2024-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_otpcode_otp_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(null=True, upload_to='accounts/images/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(null=True, upload_to='accounts/images/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='otp',
            field=models.CharField(default='f3851', max_length=6),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
