# Generated by Django 5.0.2 on 2024-04-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_doctor_image_patient_image_alter_otpcode_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='accounts/images/%Y/%m/%d/%H/%M/%S/')),
            ],
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='otp',
            field=models.CharField(default='48f1e', max_length=6),
        ),
    ]
