# Generated by Django 5.0.2 on 2024-04-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_photo_photo_image_alter_otpcode_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='otp',
            field=models.CharField(default='13669', max_length=6),
        ),
    ]
